[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "schema-org-python"
version = "0.1.0"
description = "Schema.org schemas as pydantic models"
authors = ["Arun Sharma <arun@sharma-home.net>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/adsharma/schema-org-python"
repository = "https://github.com/adsharma/schema-org-python"
keywords = ["schema.org", "pydantic", "structured-data", "json-ld", "rdf", "models"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [{ include = "schema_models" }]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/adsharma/schema-org-python/issues"

[tool.poetry.dependencies]
python = "^3.9"
fquery = "^0.4"
requests = "^2.32.5"
rdflib = "^7.5.0"
autoflake = "^2.3.1"

[tool.poetry.group.dev-dependencies.dependencies]
pytest = "^7.1.2"
pytest-cov = "^4.0.0"
black = "^24.10.0"
isort = "^5.13.2"
flake8 = "^7.1.1"

[tool.isort]
profile = "black"
