from typing import List, Optional, Union

from schema_models.article import Article


class Report(Article):
    """
    A Report generated by governmental or non-governmental organization.
    """

    reportNumber: Optional[Union[str, List[str]]] = None
